### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [RhysJackson/googleKubernetesR#3]
Just enquiring if the current licensing is to be decided - at the moment the license field in the DESCRIPTION I think isn't CRAN compliant.

I use MIT which is as permissive as you can get I think, but obviously thats up to you. 

If MIT was ok it would involve changing this line:

```
License: Year: 2017 Copyright Holder: Rhys Jackson
```

to:

```
License: MIT + file LICENSE
```

**Comment by RhysJackson** [comment]
Thanks for the suggestion - happy to change the licensing. This has been implemented in https://github.com/RhysJackson/googleKubernetesR/commit/b47789bf178e41f3fc088c1bfcbab8c476cffa3d
